### ISSUE TITLE
POSHKnife fails to upload a cookbook with a long description containing sample JSON usage

### ISSUE THREAD

**Issue by JamesDawson** [POSHChef/POSHChef#19]
The generated README.md file contains some sample JSON for how to consume the cookbook in a runlist:

``` JSON
{
  "name": "MyCookbook",
  "run_list": [
    "recipe[MyCookbook]"
  ]
}
```

Upon uploading the cookbook, POSHKnife reports no errors, but new (or updated) cookbook is not visible when checking the Chef server.  Running Fiddler shows a 400 error returned by the server reporting invalid JSON.  Further investigation showed that the "recipe[MyCookbook]" string was being split across multiple lines:

```
"recipe[
MyCookbook]"
```

This issue seems only to occur when running POSHKnife under Powershell v3.

**Comment by russellseymour** [comment]
After some testing it seems that the `ConvertTo-JSON` cmdlet behaves slightly different in PS 3 as it does in PS 4.

Adding the `-Compress` switch to the argument fixes the issue.
